location = /ALKASH-TRANS {
  return 301 /ALKASH-TRANS/;
}

location ^~ /ALKASH-TRANS/assets/ {
  alias /var/www/alkash-trans-site/assets/;
}

location ^~ /ALKASH-TRANS/ {
  alias /var/www/alkash-trans-site/;
  try_files $uri $uri/ /ALKASH-TRANS/index.html;
}
